### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by outloudvi** [E103/chat#1]
Hey guy - add your GPG/PGP key here so that I can cross-sign you.

**Comment by Antimoney** [comment]
please go to https://github.com/E103/chat/issues/2 or https://e103.github.io/chat/

**Comment by Antimoney** [comment]
其实可以把不想放到web界面的内容发到这个issuel里

**Comment by Antimoney** [comment]
比如说: @outloudvi 可以用bitcoin.js高一个加密界面,可以重利用zeroid

**Comment by outloudvi** [comment]
@Antimoney I've created a repo at GitLab. If you have an account there, tell me and i'll join you to the private repo.

**Comment by Antimoney** [comment]
426
